name: Build docker

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install
        run: |
          cd apps/orbeon && ant && cd build && ls -l && cd ../../..
          cd restxq && ant  && cd build && ls -l && cd ../..
          cd WS && ant  && cd build && ls -l && cd ../..
        shell: bash

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: inseefr/stromae-db:2.0.2
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
