name: Build docker

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: install
        run: |
          ls -l
          cd apps && ant && cd ..
          cd restxq && ant && cd ..
          cd WS && ant && cd ..
          cd visualize && ant && cd ..
        shell: bash


  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: opherogel/stromae-db
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: ${{steps.version.outputs.prop}}

  